[aws]
format = "[$symbol$profile(\\($region\\))]($style) "

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[x](bold red)"

[cmd_duration]
format = "[$duration]($style) "
[docker_context]
format = "[$symbol$context]($style) "

[git_branch]
format = "[$symbol\\($branch\\)]($style) "

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[package]
format = "[$symbol$version]($style) "

[nodejs]
format = "[$symbol$version]($style) "

[time]
format = "ğŸ•™[\\[ $time \\]]($style) "

[terraform]
format= "[$symbol$workspace]($style) "
