[aws]
format = "[$symbol$profile(\\($region\\))]($style) "

[character]
error_symbol = "[x](bold red)"
success_symbol = "[âœ](bold green)"

[directory]
truncate_to_repo = false
truncation_length = 2

[cmd_duration]
format = "[$duration]($style) "
[docker_context]
format = "[$symbol$context]($style) "

[git_branch]
format = "[$symbol\\($branch\\)]($style) "

[git_status]
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
conflicted = "ğŸ³"
deleted = "ğŸ—‘"
diverged = "ï¿½"
modified = "ğŸ“"
renamed = "ğŸ‘…"
staged = '[++\($count\)](green)'
stashed = "ï¿½"
untracked = "ğŸ¤·â€"

[package]
format = "[$symbol$version]($style) "

[nodejs]
format = "[$symbol$version]($style) "

[time]
format = "ğŸ•™[\\[ $time \\]]($style) "

[terraform]
format = "[$symbol$workspace]($style) "
